#!/usr/bin/env bash
# Setup a load balancer connected to two other servers
sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
sudo sed -i '$a\\nlisten appname 0.0.0.0:80\n\tmode http\n\tstats enable' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tserver 24857-web-01 44.192.74.79\n\tserver 24857-web-02 44.200.28.66' /etc/haproxy/haproxy.cfg
sudo service haproxy start
